### ISSUE TITLE
Header checkbox un-checks when it shouldn't

### ISSUE THREAD

**Issue by mclaeysb** [jakob/TableTool#13]
Very small issue, but the 'Header' checkbox seems to always un-check when I change one of the other settings at the bottom.

**Comment by jakob** [comment]
Good point. Another issue with headers is that the names are lost when reordering columns :(

**Comment by sammarcus** [comment]
Also when deleting a column too, although I suppose by definition columns are reordered after one is deleted :) 

![screen recording 2016-12-14 at 03 19 pm](https://cloud.githubusercontent.com/assets/8689264/21199319/091b8644-c211-11e6-8f61-6b8d756f8017.gif)

**Comment by jakob** [comment]
These issues should be fixed in version 1.2 (and 1.2.1)
