### ISSUE TITLE
Make compatible with older OS X

### ISSUE THREAD

**Issue by jakob** [jakob/TableTool#14]
Table Tool only uses a handful of modern APIs. With little effort, it should be possible to make it compatible with 10.9. A bit more effort would maybe even allow us to make it compatible with macOS 10.7.

**Comment by markusgschwind** [comment]
Would be fantastic ;-) Thanks!

**Comment by jakob** [comment]
Table Tool should now be compatible with older versions of OS X. I haven't tested it, but I'd love to hear feedback. New release is available here: https://github.com/jakob/TableTool/releases/

**Comment by rwenz3l** [comment]
It runs, but It seems I can't open anything on macOS 10.9.5 (Not working for  "File-> New" and not working for "File--> Open..".

**Comment by jakob** [comment]
@rwenz3l Thanks for the feedback! I've discovered the problem and fixed it. Please download the latest release from here: https://github.com/jakob/TableTool/releases

I've tested it on macOS 10.8, and everything works as expected. If you find any further problems, please let me know!

**Comment by rwenz3l** [comment]
@jakob now it works!
