### ISSUE TITLE
Feature request: pasting data into the table

### ISSUE THREAD

**Issue by lukyanov** [jakob/TableTool#30]
Using things like Microsoft Excel or Google Sheets you can usually paste table data from the clipboard. For example, you can copy the table in one Excel book and just paste it to another.

What do you think about having this feature in the TableTool? The use case for me would look like the following. I see some data in a table in Google Sheets and decide that I need to have some part of it in a csv file. Of course, I can export the data as csv from Google Sheets and then open the file with TableTool. However, usually it is more convenient and fast just to copy-and-paste the data, if you switching between the apps back and forth.

Thank you!

**Comment by jakob** [comment]
TableTool does support copy & paste. If it doesn't work, that's a bug.

Can you let me know more details about what you are trying to do?

**Comment by lukyanov** [comment]
As far as I can see, it only supports pasting to a single cell. This is what I'm trying to do:
1) Go to Google Drive create a sample table with some data using Google Sheets
2) Select a range of rows and columns (a rectangular selection)
3) Go to TableTool and try to paste the data in the clipboard. Nothing happens for me.

**Comment by lukyanov** [comment]
Ah, ok. Now I see. It actually works when you copy rows as a whole (with all columns included).
That's good! I was just expecting that it will also work when you copy some set of columns only (which works in Excel and Google Sheets). But, nevertheless, the current behaviour covers my needs. Thank you for the app!

**Comment by fulldecent** [comment]
Please provide screenshots and a reproducible test case so that we can solve the problem and be sure that it is solved.

**Comment by fulldecent** [comment]
Closing for now. Please reopen if a test case is available.
