### ISSUE TITLE
Table header setting is lost after restoring an older version of the document

### ISSUE THREAD

**Issue by martinjankoehler** [jakob/TableTool#35]
Hello Jakob,

Steps to reproduce:
    (1) open a CSV with an autodetectable table header
    (2) Assert: table header is detected
    (3) append a table row without saving the document
    (4) click main menu "File" > Restore to the opened version
    (5) Assert: table header is detected   (Defect: this assertion failed!)

I've committed a test suite which reproduces those steps automatically.

Best regards,
Martin

**Comment by jakob** [comment]
This bug should be fixed with commit  dea7ed0
