### ISSUE TITLE
Does not detect MacRoman encoding

### ISSUE THREAD

**Issue by janhoy** [jakob/TableTool#4]
Try to load this real-life CSV: https://dl.dropboxusercontent.com/u/20080302/sample.mer

It is MacRoman encoded, nas tab as separators, has a header row and contains two lines of data.
Table Tool is not able to detect encoding.
If I save it as UTF-8, encoding is detected, but separators are not detected, neither is header row
When specifying TAB manually, it loads part of the first line, but then displays a big yellow exclamation mark but with not further error

**Comment by jakob** [comment]
Can I include this sample file as a test case in the Table Tool project?

**Comment by janhoy** [comment]
Sure, you may use it, but please pull a new copy from Dropbox, I have anonymized the phone and emails in the sample.

The file is generated by Apple's Filemaker software, thus has special Mac encodings. I think you should try to detect the encoding by attempting UTF-8 & Latin1 before trying MacRoman?

**Comment by jakob** [comment]
OK, I finally managed to fix this use case. I added the anonymised version of the CSV file as a sample file (and added a test case for it).

Version 1.1.2 should now handle MacRoman files correctly (but they might not always be detected correctly; differentiating automatically between latin-1 and MacRoman is only possible in rare cases)

You can get the latest version [here](https://github.com/jakob/TableTool/releases); version 1.1.2 should also be on the App Store soon.
