### ISSUE TITLE
Try specifying a different separator or quote.

### ISSUE THREAD

**Issue by Qrizzz** [jakob/TableTool#42]
Version 1.2 won’t let me change quotes or anything else like it was possible in version 1.1.2.

The error message popup “Try specifying a different separator or quote.” is the only thing that appears and I only can click ok

**Comment by jakob** [comment]
Thanks for your bug report. Can you send me a copy of the file you have problems with? If it is a private file, you can send it via email: jakob@eggerapps.at

**Comment by Qrizzz** [comment]
I think the problem is related to cells mixed with quotes and text. Version 1.1.2 detected those too but let me choose “none quotes” … I attached a file causing the problem. Furthermore the amount of lines and columns plays some role but I can’t figure out.

[untitled.csv.zip](https://github.com/jakob/TableTool/files/1182737/untitled.csv.zip)

**Comment by jakob** [comment]
Thanks for sending a sample file! I was able to determine the cause of the problem. Can you try this build?
[Table Tool Build 7.zip](https://github.com/jakob/TableTool/files/1182808/Table.Tool.Build.7.zip)

**Comment by Qrizzz** [comment]
Wow, that was quick. Works again like a charme 👍 Thank you!
