### ISSUE TITLE
Cannot insert in second row

### ISSUE THREAD

**Issue by diek** [jakob/TableTool#51]
I created a new file and I cannot insert anywhere except the first row. Is there something I am missing? I am using high sierra, and I have restarted my computer, restarted Table Tool.

**Comment by jakob** [comment]
In Table Tool, you need to add rows before you can enter data. So if you want to type something into the second row, just click the "add row" button, and then insert data into the second row.

**Comment by diek** [comment]
Thank you for the clarification jakob
