### ISSUE TITLE
Import via Postico (when available)

### ISSUE THREAD

**Issue by doekman** [jakob/TableTool#76]
Wouldn't it be nice if you could have a button in TableTool to have it be imported via Postico? I know, it's not too difficult:

- I have a CSV opened in TableTool
- Now I switch manually to Postico (or start it, when it's not running)
- File > Open CSV...
- Navigate to the folder which contains the CSV and select it
- For some reason Postico does not always detect the correct CSV-parameters
- (ok, last step is more something for Postico: the ability to create the table based on the CSV data)

I imagine this works via some kind of command line API, sending the path and CSV-parameters to another program, so it could work with other programs as well. Maybe a shell-command to detect if the program is installed...

It should also be possible to import the CSV via other programs, like [csvkit](https://csvkit.readthedocs.io/en/latest/) (but I'm not sure how this would work, because you need some kind of manner to specify parameters, like database and table).

**Comment by fulldecent** [comment]
Thank you for sharing. This is probably outside of the project scope. Defined at https://github.com/jakob/TableTool#mission--project-scope--contributing

But CSV export should be included in Postico.
