### ISSUE TITLE
File Support Type Name

### ISSUE THREAD

**Issue by Jason-Morcos** [jakob/TableTool#78]
When Table Tool is set as the default file opener for CSV documents, it sets a file type name that seems non-standard. Instead, Table Tool could refer to .csv files it can open as "Comma Separated Values (.csv)", more similar to how other apps refer to the file type.

<img width="271" alt="Screen Shot 2019-06-27 at 11 08 14" src="https://user-images.githubusercontent.com/10710367/60277712-1552a980-98cc-11e9-91c0-ef2be574abb6.png">
This image is an example list of how many apps refer to files they can open. The last entry is for a CSV openable in Table Tool

**Comment by fulldecent** [comment]
Could you please show where this screenshot is coming from or how to reproduce this?
